baseURL = 'https://judafa.github.io/Julien-Website/'
languageCode = 'en-us'
title = 'Julien Dallot'
theme = 'paper'
[params]
  subtitle = 'A widget'
  [params.contact]
  email = 'judafa@protonmail.com'
 